# the first exercise

کتاب خانه های مورد نیاز خود را درج میکنیم :  

In [2]:
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


سپس برای اموزش مدل خود کلاس زیر را تعریف کرده تا مطابق انچه که مورد نظر است بتواند با درنظر گرفتن 
تابع فعالساز مقدار آموزش و نیز بدست اوردن دقت و صحت  مدل را اموزش بدهد :

In [20]:

class Perceptron:
    def __init__(self, input_size):
        # Initialize weights and bias randomly
        self.weights = np.random.rand(input_size)
        self.bias = np.random.rand()

    def step_function(self, x):
        # Step activation function
        return 1 if x >= 0 else 0

    def predict(self, inputs):
        # Make a prediction
        weighted_sum = np.dot(inputs, self.weights) + self.bias
        return self.step_function(weighted_sum)

    def update_weights(self, inputs, target, learning_rate):
        # Update weights based on the perceptron learning rule
        prediction = self.predict(inputs)
        error = target - prediction
        self.weights += learning_rate * error * inputs
        self.bias += learning_rate * error

    def train(self, training_data, epochs, learning_rate):
        # Train the perceptron
        for epoch in range(epochs):
            for inputs, target in training_data:
                self.update_weights(inputs, target, learning_rate)

    def calculate_accuracy(self, test_data):
        # Calculate accuracy on test data
        correct_predictions = 0
        total_samples = len(test_data)

        for inputs, target in test_data:
            prediction = self.predict(inputs)
            if prediction == target:
                correct_predictions += 1

        accuracy = correct_predictions / total_samples
        return accuracy

      
        

افزودن دیتا ها و بررسی کلید ها :

In [4]:
data = pd.read_csv('data_L_H.csv', sep = ',', header = 0)
print(data.keys())

Index(['x_point', 'y_point', 'label'], dtype='object')


ابتدا داده ها را از دیتا فریم خارج کرده و انها را ارایه ای میکنیم
بعد از ان مقداری اعشاری داده و سپس به داده های تست و ترین تقسیم بندی میشوند 

In [5]:
X = data[['x_point', 'y_point']].values
y = data['label'].values
X = X.astype(float)
y = y.astype(float)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.76, random_state=42)



یکی از موارد ضروری ورودی کلاس سایز ورودی است : 

In [14]:
input_size = X_train.shape[1]
input_size

2

اماده سازی

In [15]:
perceptron = Perceptron(input_size)

بخشی که در ادامه می اید ضروری نیست اما برای نمایش بهتر  و نیز استفاده راحت تر که لیبل هر داده در کنار ان باشد
به کمک ما می اید 

In [16]:

training_data = list(zip(X_train, y_train))
training_data



[(array([16.,  8.]), 1.0),
 (array([12., 10.]), 0.0),
 (array([2., 7.]), 1.0),
 (array([1., 7.]), 1.0),
 (array([15., 10.]), 0.0),
 (array([20., 10.]), 0.0),
 (array([ 0., 10.]), 0.0),
 (array([9., 3.]), 1.0),
 (array([0., 3.]), 1.0),
 (array([10.,  0.]), 1.0),
 (array([7., 2.]), 1.0),
 (array([7., 9.]), 0.0),
 (array([14., -1.]), 0.0),
 (array([5., 4.]), 0.0),
 (array([19.,  4.]), 1.0),
 (array([15.,  5.]), 1.0),
 (array([2., 9.]), 1.0),
 (array([1., 0.]), 1.0),
 (array([3., 2.]), 1.0),
 (array([2., 6.]), 1.0),
 (array([4., 0.]), 1.0),
 (array([11., 10.]), 0.0),
 (array([ 7., 10.]), 0.0),
 (array([20.,  4.]), 0.0),
 (array([6., 1.]), 1.0),
 (array([12., -1.]), 0.0),
 (array([13.,  5.]), 1.0),
 (array([4., 9.]), 0.0),
 (array([3., 9.]), 1.0),
 (array([19.,  2.]), 1.0),
 (array([ 4., -1.]), 0.0),
 (array([14.,  8.]), 0.0),
 (array([2., 4.]), 1.0),
 (array([20., 11.]), 0.0),
 (array([16.,  3.]), 1.0),
 (array([19., -1.]), 0.0),
 (array([0., 0.]), 1.0),
 (array([ 4., 10.]), 0.0),
 (array(

اموزش مدل‌:

In [17]:
perceptron.train(training_data, epochs=1000, learning_rate=0.1)


اماده سازی داده تست و نهایتا بررسی صحت : 

In [21]:
testing_data = list(zip(X_test, y_test))

In [22]:
accuracy = perceptron.calculate_accuracy(testing_data)

print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 50.98%
